title: Justin's Blog
email: justin@karneges.com
description: >
  This is Justin's personal blog, containing posts about software development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jblog.andbit.net" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year/:month/:day/:title/
timezone: UTC
excerpt_separator: <!--more-->
twitter_username: jkarneges
github_username: jkarneges

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
